@isTest
public class TestAddMemberCont {
    
    @isTest
    static public void TestAddMember()
    {
        
		AddMemberCont addMember= new AddMemberCont();
        addMember.societyID = '0016F00001w4VTR';
        
        //addMember.cont[0].selected = true;
        addMember.AddMember();
        
        
    //System.assertNotEquals(null,pref,'Null Page reference received');
        
    }

}